# Generated by Django 5.1.4 on 2024-12-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobboard',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
